apiVersion: v1
kind: Service
metadata:
  name: row-service
  namespace: leakplanting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    name: http
  selector:
    app: row-service
