apiVersion: v1
kind: Service
metadata:
  name: row-service
  namespace: leakplanting
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: row-service
