apiVersion: v1
kind: Service
metadata:
  name: row-service
  namespace: leakplanting
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 30001  # This will expose the service on port 30001 on all nodes
  selector:
    app: row-service
