name: Snyk Code Check

on:
  push:
    branches:
      - main

jobs:
  snyk-code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install flask

      - name: Upgrade pip
        run: |
          . venv/bin/activate
          pip install --upgrade pip

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://static.snyk.io/cli/v1.108.0/snyk-linux
          chmod +x snyk
          mv snyk /usr/local/bin/

      - name: Run Snyk Code Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test
